# Generated by Django 3.1.1 on 2020-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog',
            field=models.TextField(default=' '),
        ),
    ]
