# Generated by Django 3.1.1 on 2020-09-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog',
        ),
    ]
